Repository nextcloud/talk-ios, pull requests merged in 2018-08, with the labels that each got.

#134 Last message support
  VideoCalls/Base.lproj/Main.storyboard
  VideoCalls/NCChatMessage.h
  VideoCalls/NCChatMessage.m
  VideoCalls/NCRoom.h
  VideoCalls/NCRoom.m
  VideoCalls/NCSettingsController.h
  VideoCalls/NCSettingsController.m
  VideoCalls/RoomTableViewCell.h
  VideoCalls/RoomTableViewCell.m
  VideoCalls/RoomsTableViewController.m
  VideoCalls/RoundedNumberView.h
  VideoCalls/RoundedNumberView.m
Labels: design, enhancement

#138 System messages.
  VideoCalls.xcodeproj/project.pbxproj
  VideoCalls/ChatMessageTableViewCell.m
  VideoCalls/NCChatMessage.h
  VideoCalls/NCChatMessage.m
  VideoCalls/NCChatViewController.m
  VideoCalls/SystemMessageTableViewCell.h
  VideoCalls/SystemMessageTableViewCell.m
Labels: design, enhancement

#139 Favorite rooms
  VideoCalls/Base.lproj/Main.storyboard
  VideoCalls/Images.xcassets/favorite-action.imageset/Contents.json
  VideoCalls/Images.xcassets/favorite-action.imageset/favorite-action.png
  VideoCalls/Images.xcassets/favorite-action.imageset/favorite-action@2x.png
  VideoCalls/Images.xcassets/favorite-action.imageset/favorite-action@3x.png
  VideoCalls/Images.xcassets/favorite-room.imageset/Contents.json
  VideoCalls/Images.xcassets/favorite-room.imageset/favorite-room.png
  VideoCalls/Images.xcassets/favorite-room.imageset/favorite-room@2x.png
  VideoCalls/Images.xcassets/favorite-room.imageset/favorite-room@3x.png
  VideoCalls/NCAPIController.h
  VideoCalls/NCAPIController.m
  VideoCalls/NCRoom.h
  VideoCalls/NCRoom.m
  VideoCalls/RoomTableViewCell.h
  VideoCalls/RoomTableViewCell.m
  VideoCalls/RoomsTableViewController.m
Labels: enhancement

#140 Conversation info view improvements
  VideoCalls/HeaderWithButton.xib
  VideoCalls/Images.xcassets/exit-action.imageset/Contents.json
  VideoCalls/Images.xcassets/exit-action.imageset/exit-action.png
  VideoCalls/Images.xcassets/exit-action.imageset/exit-action@2x.png
  VideoCalls/Images.xcassets/exit-action.imageset/exit-action@3x.png
  VideoCalls/Images.xcassets/fav-off-setting.imageset/Contents.json
  VideoCalls/Images.xcassets/fav-off-setting.imageset/fav-off-setting.png
  VideoCalls/Images.xcassets/fav-off-setting.imageset/fav-off-setting@2x.png
  VideoCalls/Images.xcassets/fav-off-setting.imageset/fav-off-setting@3x.png
  VideoCalls/Images.xcassets/fav-setting.imageset/Contents.json
  VideoCalls/Images.xcassets/fav-setting.imageset/fav-setting.png
  VideoCalls/Images.xcassets/fav-setting.imageset/fav-setting@2x.png
  VideoCalls/Images.xcassets/fav-setting.imageset/fav-setting@3x.png
  VideoCalls/NCUserInterfaceController.h
  VideoCalls/NCUserInterfaceController.m
  VideoCalls/RoomCreation2TableViewController.m
  VideoCalls/RoomInfoTableViewController.m
  VideoCalls/RoomNameTableViewCell.h
  VideoCalls/RoomNameTableViewCell.m
  VideoCalls/RoomNameTableViewCell.xib
  VideoCalls/RoomsTableViewController.m
Labels: enhancement

#147 Fix wording and typo on log in page
  VideoCalls/LoginViewController.m
Labels: 3. to review, bug

#146 Show shared files previews.
  VideoCalls.xcodeproj/project.pbxproj
  VideoCalls/FileMessageTableViewCell.h
  VideoCalls/FileMessageTableViewCell.m
  VideoCalls/Images.xcassets/file-default-preview.imageset/Contents.json
  VideoCalls/Images.xcassets/file-default-preview.imageset/file-default-preview.png
  VideoCalls/Images.xcassets/file-default-preview.imageset/file-default-preview@2x.png
  VideoCalls/Images.xcassets/file-default-preview.imageset/file-default-preview@3x.png
  VideoCalls/NCAPIController.m
  VideoCalls/NCChatMessage.h
  VideoCalls/NCChatMessage.m
  VideoCalls/NCChatViewController.m
  VideoCalls/NCFilePreviewSessionManager.h
  VideoCalls/NCFilePreviewSessionManager.m
  VideoCalls/NCMessageParameter.m
Labels: 2. developing, enhancement
