Repository nextcloud/talk-ios, pull requests merged in 2022-05, with the labels that each got.

#802 Fix a text string
  NextcloudTalk/en.lproj/Localizable.strings
  ShareExtension/ShareViewController.m
Labels: l10n/i18n Translation

#800 Respect the disabled calls setting
  NextcloudTalk/NCChatViewController.m
  NextcloudTalk/NCDatabaseManager.m
  NextcloudTalk/NCSettingsController.h
  NextcloudTalk/NCSettingsController.m
  NextcloudTalk/RoomInfoTableViewController.m
  NextcloudTalk/ServerCapabilities.h
Labels: bug, enhancement, 3. to review

#804 Finish circles support
  NextcloudTalk/NCRoomParticipant.h
  NextcloudTalk/NCRoomParticipants.m
  NextcloudTalk/RoomInfoTableViewController.m
  NextcloudTalk/en.lproj/Localizable.strings
Labels: bug, 3. to review
