Repository nextcloud/talk-ios, pull requests merged in 2024-11, with the labels that each got.

#1315 Add markdown formatting menu
  .pyspelling.wordlist.txt
  NextcloudTalk/InputbarViewController.swift
  NextcloudTalk/en.lproj/Localizable.strings
Labels: feedback-requested

#1786 Continuous Voice recording
  NextcloudTalk.xcodeproj/project.pbxproj
  NextcloudTalk/BaseChatViewController.swift
  NextcloudTalk/ExpandedVoiceMessageRecordingView.swift
Labels: 3. to review

#1875 Remove NotificationCenter observer when leaving chat
  NextcloudTalk/ChatViewController.swift
Labels: backport-request
